apiVersion: v1
kind: ConfigMap
metadata:
  name: general-config
data:
  ENVIRONMENT: local
  APP_NAME: aci_api_service
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  
  ENGINE: pymysql
  DATABASE_TYPE: mysql
  DATABASE_HOST: mysql.aci.svc.cluster.local
  DATABASE_PORT: "3306"
  DATABASE_NAME: database_app

  COLLECTOR: http://otel-collector-collector.default.svc.cluster.local:4317

  VITE_DEFAULT_URL: "http://a87e9ea8b018e483597695f4e680202a-384004553.us-east-1.elb.amazonaws.com:8000"