name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          TAG=${{ github.sha }}
          docker build -t aci-apic:$TAG ./back
          docker tag aci-apic:$TAG 337909775686.dkr.ecr.us-east-1.amazonaws.com/prod/aci-apic:$TAG
          docker push 337909775686.dkr.ecr.us-east-1.amazonaws.com/prod/aci-apic:$TAG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name <your-cluster-name>

      - name: List files in k8s directory
        run: ls -la k8s

      - name: Deploy to EKS
        run: |
          sed -i.bak "s|DOCKER_IMAGE|337909775686.dkr.ecr.us-east-1.amazonaws.com/prod/aci-apic:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f ./k8s/deployment.yaml
