name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 98.84.170.141
          username: root
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/app"
          strip_components: 1
          overwrite: true

      - name: Run Docker Compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 98.84.170.141
          username: root
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            docker-compose up -d --build
